name: Upload coverage reports to Codecov
on:
    pull_request:
        branches: [main, develop]
jobs: 
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: codecov/codecov-action@v2
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
